-- Apply missing RLS policies: dev -> test
-- Generated 2026-03-05 18:15:46 UTC
-- Run this script on the TARGET database (e.g. Supabase SQL Editor or psql).
-- Missing policies: 39

-- Ensure RLS is enabled on tables that have missing policies
ALTER TABLE "public"."assignment_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."batch_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."batch_curriculum_progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."csr_activities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."discount_credits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."employee_attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."employees" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."global_promotions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."news_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."package_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."parents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."privacy_policy_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."promotion_codes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."seasonal_camp_consent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."shared_resource_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."shared_resources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_checkins" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_milestones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_portal_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."student_teacher_assignments" ENABLE ROW LEVEL SECURITY;

-- Create missing policies
CREATE POLICY "Assignment comments viewable by participants" ON public.assignment_comments FOR SELECT TO authenticated USING (((EXISTS ( SELECT 1    FROM student_assignments sa   WHERE ((sa.id = assignment_comments.assignment_id) AND ((sa.teacher_id = auth.uid()) OR is_parent_of_student(auth.uid(), sa.student_id))))) OR is_super_admin(auth.uid()) OR has_role(auth.uid(), 'csr'::app_role)));
CREATE POLICY "Participants can add comments" ON public.assignment_comments FOR INSERT TO authenticated WITH CHECK (((author_id = auth.uid()) AND ((EXISTS ( SELECT 1    FROM student_assignments sa   WHERE ((sa.id = assignment_comments.assignment_id) AND ((sa.teacher_id = auth.uid()) OR is_parent_of_student(auth.uid(), sa.student_id))))) OR is_super_admin(auth.uid()))));
CREATE POLICY "Admins and CSRs can manage all attendance" ON public.batch_attendance FOR ALL TO public USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role, 'csr'::app_role, 'hr'::app_role]))))));
CREATE POLICY "Teachers can mark attendance for their batches" ON public.batch_attendance FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1    FROM batches b   WHERE ((b.id = batch_attendance.batch_id) AND ((b.teacher_id = auth.uid()) OR (((b.metadata ->> 'teacher_ids'::text))::jsonb ? (auth.uid())::text))))));
CREATE POLICY "Teachers can update attendance for their batches" ON public.batch_attendance FOR UPDATE TO public USING ((EXISTS ( SELECT 1    FROM batches b   WHERE ((b.id = batch_attendance.batch_id) AND ((b.teacher_id = auth.uid()) OR (((b.metadata ->> 'teacher_ids'::text))::jsonb ? (auth.uid())::text))))));
CREATE POLICY "Teachers can view attendance for their batches" ON public.batch_attendance FOR SELECT TO public USING ((EXISTS ( SELECT 1    FROM batches b   WHERE ((b.id = batch_attendance.batch_id) AND ((b.teacher_id = auth.uid()) OR (((b.metadata ->> 'teacher_ids'::text))::jsonb ? (auth.uid())::text))))));
CREATE POLICY "Teachers can manage their batch curriculum" ON public.batch_curriculum_progress FOR ALL TO authenticated USING ((has_role(auth.uid(), 'teacher'::app_role) AND (EXISTS ( SELECT 1    FROM batches   WHERE ((batches.id = batch_curriculum_progress.batch_id) AND (batches.teacher_id = auth.uid()))))));
CREATE POLICY "Authenticated users can log activities" ON public.csr_activities FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['super_admin'::app_role, 'center_admin'::app_role, 'csr'::app_role, 'crm'::app_role]))))));
CREATE POLICY "Staff can view activities" ON public.csr_activities FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['staff'::app_role, 'csr'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'global_csr'::app_role, 'crm'::app_role]))))));
CREATE POLICY "Users can view activities" ON public.csr_activities FOR SELECT TO authenticated USING (((performed_by = auth.uid()) OR (EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['super_admin'::app_role, 'center_admin'::app_role, 'csr'::app_role, 'crm'::app_role])))))));
CREATE POLICY "Staff can view discount credits" ON public.discount_credits FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['staff'::app_role, 'csr'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'global_csr'::app_role, 'accounts'::app_role]))))));
CREATE POLICY "Employees can insert their own attendance" ON public.employee_attendance FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1    FROM employees e   WHERE ((e.id = employee_attendance.employee_id) AND (lower(e.email) = lower(get_current_user_email())) AND (e.deleted_at IS NULL)))));
CREATE POLICY "HR can delete employee attendance for assigned centers" ON public.employee_attendance FOR DELETE TO authenticated USING ((has_role(auth.uid(), 'hr'::app_role) AND ((NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid())))) OR (EXISTS ( SELECT 1    FROM user_learning_centers ulc   WHERE ((ulc.user_id = auth.uid()) AND (ulc.center_id = employee_attendance.learning_center_id)))))));
CREATE POLICY "Allow authorized staff to insert employees" ON public.employees FOR INSERT TO authenticated WITH CHECK ((is_super_admin(auth.uid()) OR (EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'csr'::app_role, 'global_csr'::app_role, 'crm'::app_role, 'cms'::app_role])))))));
CREATE POLICY "Staff can view employees" ON public.employees FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['staff'::app_role, 'csr'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'global_csr'::app_role]))))));
CREATE POLICY "Users can view employees" ON public.employees FOR SELECT TO authenticated USING ((is_super_admin(auth.uid()) OR has_role(auth.uid(), 'global_csr'::app_role) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND ((center_ids IS NULL) OR (array_length(center_ids, 1) IS NULL) OR (array_length(center_ids, 1) = 0) OR (EXISTS ( SELECT 1    FROM unnest(employees.center_ids) emp_center(emp_center)   WHERE user_has_center_access(auth.uid(), emp_center.emp_center)))))));
CREATE POLICY "Admins can manage global promotions" ON public.global_promotions FOR ALL TO public USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role, 'cms'::app_role]))))));
CREATE POLICY "Parents can view their news events" ON public.news_events FOR SELECT TO authenticated USING (((status = 'published'::text) AND ((audience_scope = 'global'::text) OR ((audience_scope = 'learning_center'::text) AND (EXISTS ( SELECT 1    FROM ((enrollments e      JOIN students s ON ((s.id = e.student_id)))      JOIN parents p ON ((p.id = s.parent_id_new)))   WHERE ((p.id = get_parent_id_by_auth_email()) AND (e.center_id = ANY (news_events.center_ids)) AND (e.deleted_at IS NULL))))) OR ((audience_scope = ANY (ARRAY['specific_customers'::text, 'single_customer'::text])) AND (get_parent_id_by_auth_email() = ANY (customer_ids))))));
CREATE POLICY "Anyone can view messages for accessible packages" ON public.package_messages FOR SELECT TO public USING (((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role, 'csr'::app_role, 'global_csr'::app_role]))))) OR (EXISTS ( SELECT 1    FROM custom_packages cp   WHERE ((cp.id = package_messages.package_id) AND (lower(cp.customer_email) = lower((( SELECT users.email            FROM auth.users           WHERE (users.id = auth.uid())))::text)))))));
CREATE POLICY "CSR can insert messages" ON public.package_messages FOR INSERT TO public WITH CHECK (((sender_type = 'csr'::text) AND (EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role, 'csr'::app_role, 'global_csr'::app_role])))))));
CREATE POLICY "CSR can view parents in their scope" ON public.parents FOR SELECT TO authenticated USING ((is_super_admin(auth.uid()) OR has_role(auth.uid(), 'global_csr'::app_role) OR ((has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND (id IN ( SELECT students.parent_id_new    FROM students   WHERE (students.id IN ( SELECT enrollments.student_id            FROM enrollments           WHERE user_has_center_access(auth.uid(), enrollments.center_id))))))));
CREATE POLICY "Front desk can view parents in their centers" ON public.parents FOR SELECT TO authenticated USING ((has_role(auth.uid(), 'frontdesk'::text) AND ((NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid())))) OR (EXISTS ( SELECT 1    FROM ((students s      JOIN enrollments e ON ((e.student_id = s.id)))      JOIN user_learning_centers ulc ON ((ulc.center_id = e.center_id)))   WHERE ((s.parent_id_new = parents.id) AND (ulc.user_id = auth.uid()) AND (e.deleted_at IS NULL) AND (s.deleted_at IS NULL)))) OR (EXISTS ( SELECT 1    FROM (child_attendance ca      JOIN user_learning_centers ulc ON ((ulc.center_id = ca.learning_center_id)))   WHERE ((ca.parent_id = parents.id) AND (ulc.user_id = auth.uid()))))) AND (deleted_at IS NULL)));
CREATE POLICY "Parents: CSR access by center" ON public.parents FOR ALL TO authenticated USING ((has_role(auth.uid(), 'csr'::app_role) AND ((NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid())))) OR parent_in_user_centers(id, auth.uid()))));
CREATE POLICY "Staff can view parents" ON public.parents FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['staff'::app_role, 'csr'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'global_csr'::app_role, 'crm'::app_role]))))));
CREATE POLICY "Teachers can view parents of their batch students" ON public.parents FOR SELECT TO public USING ((EXISTS ( SELECT 1    FROM ((students s      JOIN batch_students bs ON ((bs.student_id = s.id)))      JOIN batches b ON ((b.id = bs.batch_id)))   WHERE ((s.parent_id_new = parents.id) AND (b.teacher_id = auth.uid()) AND (bs.status = 'active'::text) AND (s.deleted_at IS NULL) AND (parents.deleted_at IS NULL)))));
CREATE POLICY "Payments: Staff can manage through enrollments" ON public.payments FOR ALL TO public USING ((is_super_admin(auth.uid()) OR has_role(auth.uid(), 'global_csr'::app_role) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND (NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid()))))) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND payment_in_user_centers(enrollment_id, auth.uid()))));
CREATE POLICY "Only admins can delete privacy policy sections" ON public.privacy_policy_sections FOR DELETE TO public USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = 'admin'::app_role)))));
CREATE POLICY "Users can view profiles in their scope" ON public.profiles FOR SELECT TO public USING (((id = auth.uid()) OR is_super_admin(auth.uid()) OR has_role(auth.uid(), 'global_csr'::app_role) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND (NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid()))))) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR has_role(auth.uid(), 'crm'::app_role)) AND (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid()))) AND (EXISTS ( SELECT 1    FROM (user_learning_centers ulc_viewer      JOIN user_learning_centers ulc_target ON ((ulc_viewer.center_id = ulc_target.center_id)))   WHERE ((ulc_viewer.user_id = auth.uid()) AND (ulc_target.user_id = profiles.id)))))));
CREATE POLICY "Staff can view promo codes" ON public.promotion_codes FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['staff'::app_role, 'csr'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'global_csr'::app_role, 'accounts'::app_role]))))));
CREATE POLICY "CMS users can delete consent" ON public.seasonal_camp_consent FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['cms'::app_role, 'admin'::app_role, 'super_admin'::app_role]))))));
CREATE POLICY "CMS users can insert consent" ON public.seasonal_camp_consent FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['cms'::app_role, 'admin'::app_role, 'super_admin'::app_role]))))));
CREATE POLICY "Shared resource files follow parent resource access" ON public.shared_resource_files FOR SELECT TO public USING ((EXISTS ( SELECT 1    FROM shared_resources sr   WHERE (sr.id = shared_resource_files.resource_id))));
CREATE POLICY "Students can view shared resources" ON public.shared_resources FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1    FROM (batch_students bs      JOIN students s ON ((s.id = bs.student_id)))   WHERE ((bs.batch_id = shared_resources.batch_id) AND (bs.status = 'active'::text) AND (s.deleted_at IS NULL) AND is_parent_of_student(auth.uid(), s.id)))));
CREATE POLICY "Teachers can manage assignments" ON public.student_assignments FOR ALL TO public USING ((EXISTS ( SELECT 1    FROM user_roles   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['teacher'::app_role, 'admin'::app_role, 'super_admin'::app_role, 'csr'::app_role]))))));
CREATE POLICY "Staff can view checkins in their centers" ON public.student_checkins FOR SELECT TO public USING ((is_super_admin(auth.uid()) OR has_role(auth.uid(), 'global_csr'::app_role) OR ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'staff'::app_role) OR has_role(auth.uid(), 'frontdesk'::app_role) OR has_role(auth.uid(), 'teacher'::app_role)) AND user_has_center_access(auth.uid(), center_id)) OR (student_id IN ( SELECT students.id    FROM students   WHERE (students.parent_id_new = auth.uid())))));
CREATE POLICY "Teachers can create milestones for their students" ON public.student_milestones FOR INSERT TO public WITH CHECK (((teacher_id = auth.uid()) OR (EXISTS ( SELECT 1    FROM (batches b      JOIN batch_students bs ON ((b.id = bs.batch_id)))   WHERE ((b.teacher_id = auth.uid()) AND (bs.student_id = student_milestones.student_id) AND (bs.status = 'active'::text))))));
CREATE POLICY "Admins can manage all credentials" ON public.student_portal_credentials FOR ALL TO authenticated USING ((EXISTS ( SELECT 1    FROM user_roles ur   WHERE ((ur.user_id = auth.uid()) AND (ur.role = ANY (ARRAY['super_admin'::app_role, 'admin'::app_role, 'csr'::app_role]))))));
CREATE POLICY "Parents can update own credentials" ON public.student_portal_credentials FOR UPDATE TO authenticated USING ((parent_id IN ( SELECT p.id    FROM parents p   WHERE ((lower(p.email) = lower(( SELECT (auth.jwt() ->> 'email'::text)))) AND (p.deleted_at IS NULL)))));
CREATE POLICY "Staff can manage assignments in their centers" ON public.student_teacher_assignments FOR ALL TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'csr'::app_role) OR (has_role(auth.uid(), 'crm'::app_role) AND ((NOT (EXISTS ( SELECT 1    FROM user_learning_centers   WHERE (user_learning_centers.user_id = auth.uid())))) OR (batch_id IN ( SELECT batches.id    FROM batches   WHERE (batches.center_id IN ( SELECT user_learning_centers.center_id            FROM user_learning_centers           WHERE (user_learning_centers.user_id = auth.uid())))))))));
